// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl3eZ6OhyfN64ARLNoRqBB3K-Cnk-5gfM',
    appId: '1:387319931088:web:cb7e9617507e2dee997ed5',
    messagingSenderId: '387319931088',
    projectId: 'niyojan-e1cbf',
    authDomain: 'niyojan-e1cbf.firebaseapp.com',
    storageBucket: 'niyojan-e1cbf.firebasestorage.app',
    measurementId: 'G-WQXGHKYHPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBCCHc-YkbmIEwj4XIOGVmhpw7bMwWRyc',
    appId: '1:387319931088:android:b2f8401e7d110914997ed5',
    messagingSenderId: '387319931088',
    projectId: 'niyojan-e1cbf',
    storageBucket: 'niyojan-e1cbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFBIaCqoR3SHepIWvfZ3bIzJ-iypVnvMc',
    appId: '1:387319931088:ios:46d667ceabb282bc997ed5',
    messagingSenderId: '387319931088',
    projectId: 'niyojan-e1cbf',
    storageBucket: 'niyojan-e1cbf.firebasestorage.app',
    iosBundleId: 'com.example.niyojan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFBIaCqoR3SHepIWvfZ3bIzJ-iypVnvMc',
    appId: '1:387319931088:ios:46d667ceabb282bc997ed5',
    messagingSenderId: '387319931088',
    projectId: 'niyojan-e1cbf',
    storageBucket: 'niyojan-e1cbf.firebasestorage.app',
    iosBundleId: 'com.example.niyojan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl3eZ6OhyfN64ARLNoRqBB3K-Cnk-5gfM',
    appId: '1:387319931088:web:ff86bae7107a427e997ed5',
    messagingSenderId: '387319931088',
    projectId: 'niyojan-e1cbf',
    authDomain: 'niyojan-e1cbf.firebaseapp.com',
    storageBucket: 'niyojan-e1cbf.firebasestorage.app',
    measurementId: 'G-CN562SJ0F0',
  );
}
